/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvoicesRejectedRouteImport } from './routes/invoices.rejected'
import { Route as InvoicesPendingRouteImport } from './routes/invoices.pending'
import { Route as InvoicesEntryRouteImport } from './routes/invoices.entry'
import { Route as InvoicesApprovedRouteImport } from './routes/invoices.approved'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices.$invoiceId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRejectedRoute = InvoicesRejectedRouteImport.update({
  id: '/invoices/rejected',
  path: '/invoices/rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesPendingRoute = InvoicesPendingRouteImport.update({
  id: '/invoices/pending',
  path: '/invoices/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesEntryRoute = InvoicesEntryRouteImport.update({
  id: '/invoices/entry',
  path: '/invoices/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesApprovedRoute = InvoicesApprovedRouteImport.update({
  id: '/invoices/approved',
  path: '/invoices/approved',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/approved': typeof InvoicesApprovedRoute
  '/invoices/entry': typeof InvoicesEntryRoute
  '/invoices/pending': typeof InvoicesPendingRoute
  '/invoices/rejected': typeof InvoicesRejectedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/approved': typeof InvoicesApprovedRoute
  '/invoices/entry': typeof InvoicesEntryRoute
  '/invoices/pending': typeof InvoicesPendingRoute
  '/invoices/rejected': typeof InvoicesRejectedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/approved': typeof InvoicesApprovedRoute
  '/invoices/entry': typeof InvoicesEntryRoute
  '/invoices/pending': typeof InvoicesPendingRoute
  '/invoices/rejected': typeof InvoicesRejectedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reports'
    | '/search'
    | '/settings'
    | '/invoices/$invoiceId'
    | '/invoices/approved'
    | '/invoices/entry'
    | '/invoices/pending'
    | '/invoices/rejected'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reports'
    | '/search'
    | '/settings'
    | '/invoices/$invoiceId'
    | '/invoices/approved'
    | '/invoices/entry'
    | '/invoices/pending'
    | '/invoices/rejected'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/reports'
    | '/search'
    | '/settings'
    | '/invoices/$invoiceId'
    | '/invoices/approved'
    | '/invoices/entry'
    | '/invoices/pending'
    | '/invoices/rejected'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ReportsRoute: typeof ReportsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  InvoicesInvoiceIdRoute: typeof InvoicesInvoiceIdRoute
  InvoicesApprovedRoute: typeof InvoicesApprovedRoute
  InvoicesEntryRoute: typeof InvoicesEntryRoute
  InvoicesPendingRoute: typeof InvoicesPendingRoute
  InvoicesRejectedRoute: typeof InvoicesRejectedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/rejected': {
      id: '/invoices/rejected'
      path: '/invoices/rejected'
      fullPath: '/invoices/rejected'
      preLoaderRoute: typeof InvoicesRejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/pending': {
      id: '/invoices/pending'
      path: '/invoices/pending'
      fullPath: '/invoices/pending'
      preLoaderRoute: typeof InvoicesPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/entry': {
      id: '/invoices/entry'
      path: '/invoices/entry'
      fullPath: '/invoices/entry'
      preLoaderRoute: typeof InvoicesEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/approved': {
      id: '/invoices/approved'
      path: '/invoices/approved'
      fullPath: '/invoices/approved'
      preLoaderRoute: typeof InvoicesApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$invoiceId': {
      id: '/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ReportsRoute: ReportsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  InvoicesInvoiceIdRoute: InvoicesInvoiceIdRoute,
  InvoicesApprovedRoute: InvoicesApprovedRoute,
  InvoicesEntryRoute: InvoicesEntryRoute,
  InvoicesPendingRoute: InvoicesPendingRoute,
  InvoicesRejectedRoute: InvoicesRejectedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
